version: '2'
services:
    web:
        build: 
            context: .
            dockerfile: ./compose/flask/Dockerfile
        ports:
            - "${HTTP_PORT}:${HTTP_PORT}"
        volumes:
            - .:/code
        depends_on:
            - redis
        stdin_open: true
        tty: true
        environment:
            - HTTP_PORT=${HTTP_PORT}
    redis:
        image: redis
