version: '2'
services:
    web:
        build: 
            context: .
            dockerfile: ./compose/flask/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        stdin_open: true
        tty: true
    redis:
        image: redis
